#!/usr/bin/env bash

max=100
[ "x" != x"$1" ] && max=$1
seq 1 $max |
    while read i; do
        [  $(($i % 3)) == 0  ] &&  echo -n Fizz;
        [ $(($i % 5)) == 0 ] && echo -n Buzz;
        [ $(($i % 3)) != 0 ]  && [ $(($i % 5)) != 0 ] && echo -n $i; 
        echo "";
    done
