JCC = javac
JFLAGS = -g
JVM = java
#name:	
#	 echo "java"
#fizzbuzz: FizzBuzz.java
#	  javac -o fizzbuzz FizzBuzz.java
#exe: fizzbuzz

#FizzBuzz.class: FizzBuzz.java
#	$(JCC) $(JFLAGS) FizzBuzz.java

#name:
#	echo "javaFizz"
exe:
	java -classpath . FizzBuzz
