#!/usr/bin/env tclsh

set max 100
if { $::argc > 0 } {
    set max [lindex $::argv 0]
}

for {set i 1} {$i<=$max} {incr i} {
    if {$i % 15 == 0} {
        puts "FizzBuzz"
    } elseif { $i % 5 == 0 } {
        puts "Buzz"
    } elseif { $i % 3 == 0 } {
        puts "Fizz"
    } else {
        puts $i
    }
}

