#!/usr/bin/env bash
max=100
[ "x" != x"$1" ] && max=$1
seq 1 $max |
    awk '
    BEGIN {ORS  = ""}
    $1 % 3 == 0 {print "Fizz"}
    $1 % 5 == 0 { print "Buzz" }
    $1 % 3 != 0 && $1 % 5 != 0 { print $1 }
    {print "\n"}'
